### PR TITLE
Optimise graph

### PR DESCRIPTION
**Pull request by abtheo**
Hey @otterclamking , ready for review 😮‍💨

Reminder, this PR should be merged to the Backup subgraph for now, as it contains breaking changes for the old dashboard.

Currently syncing here https://thegraph.com/hosted-service/subgraph/abtheo/otter-development?selected=logs, should be done in around 2 hours from this post.

### CODE REVIEW

**Comment by otterclamking** [comment]
The changes are really huge. I can't even scroll to the bottom 😂

**Comment by otterclamking** [comment]
I tried to deploy to here https://thegraph.com/hosted-service/subgraph/otterclam/otterclam_backup Looks like the ID is different. @abtheo

**Comment by abtheo** [comment]
> I tried to deploy to here https://thegraph.com/hosted-service/subgraph/otterclam/otterclam_backup Looks like the ID is different. @abtheo

Hmm that's strange, I thought I deployed and pushed at the same time last night so the code should be identical.

I just found a small bug with the cumulative values not tracking the payout totals correctly, so I have pushed the latest commit and also re-deployed to my dev subgraph. This time I am 1000% sure that there is no difference between my commit and the build - I ran the commands `yarn deploy-test; git commit; git push;` all back-to-back with no changes inbetween.
image

When the latest sync on my graph is complete, could you please try re-deploying? If the ID still doesn't match then I don't think  this trick works for different Subgraph URLs 🤔

**Comment by otterclamking** [comment]
CleanShot 2022-07-22 at 16 33 49@2x

I tried query clamBacking. The value looks wired. Are we using this on new dashboard?

**Comment by abtheo** [comment]
> CleanShot 2022-07-22 at 16 33 49@2x
> 
> I tried query clamBacking. The value looks wired. Are we using this on the new dashboard?

Ah good catch, thanks. I was doing `backing = supply/assets`, should be `assets/supply` 👍

I believe the `totalMarketValueWithoutClam` is calculating correctly at least, so latest commit should fix
image

**Comment by abtheo** [comment]
@otterclamking looks like all the bugs have been hammered out 🤞 could you please sync the Backup graph from this branch again?

**Comment by otterclamking** [comment]
> @otterclamking looks like all the bugs have been hammered out 🤞 could you please sync the Backup graph from this branch again?

All good! Sync finished immediately! https://thegraph.com/hosted-service/subgraph/otterclam/otterclam_backup

**Pull request merged**
